[[http]]
name = "test-config"
bind-addr = "0.0.0.0:9096"

[[http.output]]
name="influxdb01"
location="http://influxdb:8086/prom/write"
type="prometheus"

[[http.output]]
name="influxdb02"
location="http://influxdb:8086/prom/write"
type="prometheus"
buffer-size-mb=100
max-batch-kb=1000
max-delay-interval="5s"